name: taskwarrior tests
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: checkout taskwarrior latest
      uses: actions/checkout@v3
      with:
        repository: GothenburgBitFactory/taskwarrior
        path: taskwarrior

    - uses: actions/cache@v3
      with:
        path: ./taskwarrior/build
        key: taskwarrior-build-${{ hashFiles('./taskwarrior/CMakeLists.txt') }}

    - name: build taskwarrior
      working-directory: ./taskwarrior
      run: |
        if [ -d "build" ]; then
          exit 0
        fi
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build build
      shell: bash

    - name: create config
      working-directory: ./taskwarrior
      run: |
        touch $HOME/.taskrc
        echo data.location=./taskwarrior/.task >> $HOME/.taskrc

    - name: checkout testcode
      uses: actions/checkout@v3

    - name: set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('./requirements.txt') }}

    - name: install Python dependencies
      run: |
        pip3 install -r requirements.txt
      shell: bash

    - name: debug
      run: |
        ls
        ls ./testwarrior
        ls ./testwarrior/build
        ls ./testwarrior/build/src
      shell: bash

    - name: run the tests
      run: |
        pytest -s -v
      shell: bash
      env:
        TASKW_PATH: ${{ github.workspace }}/taskwarrior/build/src




