name: taskwarrior tests
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: checkout taskwarrior latest
      uses: actions/checkout@v3
      with:
        repository: GothenburgBitFactory/taskwarrior
        path: taskwarrior

    - uses: actions/cache@v3
      with:
        path: ./taskwarrior/build
        key: taskwarrior-build-${{ hashFiles('./taskwarrior/CMakeLists.txt') }}

    - name: build taskwarrior
      working-directory: ./taskwarrior
      run: |
        if [ -d "build" ]; then
          exit 0
        fi
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build build
      shell: bash

    - name: trial run
      working-directory: ./taskwarrior
      run: |
        touch $HOME/.taskrc
        echo data.location=/Users/stuart.duffy/.task >> $HOME/.taskrc
        ./build/src/task add baloney


