name: taskwarrior tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    # - name: checkout taskwarrior latest
    #   uses: actions/checkout@v3
    #   with:
    #     repository: GothenburgBitFactory/taskwarrior
    #     path: taskwarrior

    # - uses: actions/cache@v3
    #   with:
    #     path: ./taskwarrior/build
    #     key: taskwarrior-build

    # - name: build taskwarrior
    #   working-directory: ./taskwarrior
    #   run: |
    #     cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
    #     cmake --build build
    #   shell: bash

    - name: get taskwarrior release
      run: |
        mkdir taskwarrior
        cd taskwarrior
        gh release download --pattern '*.gz' --repo GothenburgBitFactory/taskwarrior
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
