name: fakestoreapi tests
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout testcode
      uses: actions/checkout@v3
      with:
        path: pytest-tests

    - name: set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('./pytest-tests/requirements.txt') }}

    - name: install Python dependencies
      working-directory: ./pytest-tests
      run: |
        pip3 install -r requirements.txt
      shell: bash

    - name: run the tests
      working-directory: ./pytest-tests
      run: |
        pytest ./tests/test_fakestoreapi.py -s -v
      shell: bash
